package com.zyh.archivemind.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.zyh.archivemind.client.DeepSeekClient;
import com.zyh.archivemind.config.AiProperties;
import com.zyh.archivemind.entity.SearchResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import com.zyh.archivemind.dto.SessionDTO;

import java.time.Duration;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 * 
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {
    
    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final DeepSeekClient deepSeekClient;
    private final QueryRewriteService queryRewriteService;
    private final ConversationSessionService conversationSessionService;
    private final AiProperties aiProperties;
    private final ObjectMapper objectMapper;
    
    // 用于存储每个会话的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 停止标志 - 简单方案
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();
    // 用于累积每个会话的思考过程内容
    private final Map<String, StringBuilder> thinkingBuilders = new ConcurrentHashMap<>();
    // 存储每个 session 关联的 conversationId，避免闭包变量作用域问题（S2 修复）
    private final Map<String, String> sessionConversationIds = new ConcurrentHashMap<>();
    // 存储每个 session 关联的 userId，避免闭包变量作用域问题（S2 修复）
    private final Map<String, String> sessionUserIds = new ConcurrentHashMap<>();
    // 记录每个 session 的开始时间，用于定时清理 stale session 数据
    private final Map<String, Long> sessionStartTimes = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      HybridSearchService searchService,
                      DeepSeekClient deepSeekClient,
                      QueryRewriteService queryRewriteService,
                      ConversationSessionService conversationSessionService,
                      AiProperties aiProperties) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.deepSeekClient = deepSeekClient;
        this.queryRewriteService = queryRewriteService;
        this.conversationSessionService = conversationSessionService;
        this.aiProperties = aiProperties;
        this.objectMapper = new ObjectMapper();
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        logger.info("开始处理消息，用户ID: {}, 会话ID: {}", userId, session.getId());
        try {
            final String sessionId = session.getId();

            // 1. 获取或创建会话 ID
            String conversationId = getOrCreateConversationId(userId);
            logger.info("会话ID: {}, 用户ID: {}", conversationId, userId);

            // 初始化 session 关联数据
            responseBuilders.put(sessionId, new StringBuilder());
            thinkingBuilders.put(sessionId, new StringBuilder());
            sessionConversationIds.put(sessionId, conversationId);
            sessionUserIds.put(sessionId, userId);
            sessionStartTimes.put(sessionId, System.currentTimeMillis());

            // 2. 获取对话历史
            List<Map<String, String>> history = getConversationHistory(conversationId);
            logger.debug("获取到 {} 条历史对话", history.size());

            // 2.5 如果是第一条消息，自动生成会话标题
            if (history.isEmpty()) {
                try {
                    conversationSessionService.autoGenerateTitle(conversationId, userMessage);
                    logger.info("已为会话 {} 自动生成标题", conversationId);
                } catch (Exception e) {
                    logger.warn("自动生成标题失败，会话ID: {}, 错误: {}", conversationId, e.getMessage());
                }
            }

            // 3. Query Rewriting：结合对话历史改写当前问题，生成语义完整的检索查询
            String rewrittenQuery = queryRewriteService.rewrite(userMessage, history);
            logger.info("检索用查询: {}", rewrittenQuery);

            // 4. 使用改写后的查询执行带权限过滤的混合搜索
            List<SearchResult> searchResults = searchService.searchWithPermission(rewrittenQuery, userId, 5);
            logger.debug("搜索结果数量: {}", searchResults.size());

            // 5. 构建上下文
            String context = buildContext(searchResults);

            // 6. 调用 DeepSeek API 并处理流式响应（使用原始用户消息，保持对话自然）
            logger.info("调用DeepSeek API生成回复");
            deepSeekClient.streamResponse(userMessage, context, history,
                // onThinkingChunk - 累积思考内容并推送 thinking 类型消息
                thinkingChunk -> {
                    if (!session.isOpen()) return;
                    StringBuilder thinkingBuilder = thinkingBuilders.get(sessionId);
                    if (thinkingBuilder != null) {
                        thinkingBuilder.append(thinkingChunk);
                    }
                    sendThinkingChunk(session, thinkingChunk);
                },
                // onAnswerChunk - 累积回答内容并推送 answer 类型消息
                answerChunk -> {
                    if (!session.isOpen()) return;
                    StringBuilder responseBuilder = responseBuilders.get(sessionId);
                    if (responseBuilder != null) {
                        responseBuilder.append(answerChunk);
                    }
                    sendAnswerChunk(session, answerChunk);
                },
                // onComplete - 替换后台线程轮询逻辑
                () -> {
                    String completeResponse = responseBuilders.getOrDefault(sessionId, new StringBuilder()).toString();
                    String thinkingContent = thinkingBuilders.getOrDefault(sessionId, new StringBuilder()).toString();
                    String convId = sessionConversationIds.get(sessionId);
                    String uid = sessionUserIds.get(sessionId);

                    logger.info("DeepSeek响应已完成，回答长度: {}, 思考长度: {}", completeResponse.length(), thinkingContent.length());

                    // 发送完成通知
                    sendCompletionNotification(session);

                    // 更新对话历史（含思考过程内容）
                    if (convId != null) {
                        updateConversationHistory(convId, userMessage, completeResponse, thinkingContent);
                    }

                    // 刷新会话 TTL
                    if (uid != null && convId != null) {
                        try {
                            conversationSessionService.refreshSessionTTL(uid, convId);
                        } catch (Exception ttlEx) {
                            logger.warn("刷新会话TTL失败，用户ID: {}, 会话ID: {}, 错误: {}", uid, convId, ttlEx.getMessage());
                        }
                    }

                    // 统一清理 session 关联的临时数据
                    cleanupSession(sessionId);
                    logger.info("消息处理完成，用户ID: {}", uid);
                },
                // onError - 错误处理
                error -> {
                    handleError(session, error);
                    sendCompletionNotification(session);
                    cleanupSession(sessionId);
                }
            );

        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(session, e);
            // 清理 session 关联数据
            cleanupSession(session.getId());
        }
    }

    private String getOrCreateConversationId(String userId) {
        String conversationId = conversationSessionService.getActiveSessionId(userId);
        
        if (conversationId == null) {
            SessionDTO newSession = conversationSessionService.createSession(userId);
            conversationId = newSession.getSessionId();
            logger.info("为用户 {} 自动创建新会话: {}", userId, conversationId);
        } else {
            logger.info("获取到用户 {} 的活跃会话ID: {}", userId, conversationId);
        }
        
        return conversationId;
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        String key = "conversation:" + conversationId;
        String json = redisTemplate.opsForValue().get(key);
        try {
            if (json == null) {
                logger.debug("会话 {} 没有历史记录", conversationId);
                return new ArrayList<>();
            }
            
            List<Map<String, String>> history = objectMapper.readValue(json, new TypeReference<List<Map<String, String>>>() {});
            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    private void updateConversationHistory(String conversationId, String userMessage, 
                                           String response, String thinkingContent) {
        String key = "conversation:" + conversationId;
        List<Map<String, String>> history = getConversationHistory(conversationId);
        
        // 获取当前时间戳
        String currentTimestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
        
        // 添加用户消息（带时间戳）
        Map<String, String> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        history.add(userMsgMap);
        
        // 添加助手回复（带时间戳）
        Map<String, String> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", response);
        assistantMsgMap.put("timestamp", currentTimestamp);
        
        // 添加思考过程内容（非空时），支持截断逻辑防止 Redis 大 Key
        if (thinkingContent != null && !thinkingContent.isEmpty()) {
            int maxLen = aiProperties.getThinking().getMaxPersistLength();
            if (thinkingContent.length() > maxLen) {
                thinkingContent = thinkingContent.substring(0, maxLen) + "\n\n[思考过程内容过长，已截断]";
                logger.warn("思考过程内容超过 {} 字符，已截断", maxLen);
            }
            assistantMsgMap.put("thinkingContent", thinkingContent);
        }
        history.add(assistantMsgMap);
        
        // 限制历史记录长度，保留最近的20条消息
        if (history.size() > 20) {
            history = history.subList(history.size() - 20, history.size());
        }
        
        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, Duration.ofDays(7));
            logger.debug("更新会话历史，会话ID: {}, 总消息数: {}", conversationId, history.size());
        } catch (JsonProcessingException e) {
            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private String buildContext(List<SearchResult> searchResults) {
        if (searchResults == null || searchResults.isEmpty()) {
            // 返回空字符串，让 DeepSeekClient 按"无检索结果"逻辑处理
            return "";
        }

        final int MAX_SNIPPET_LEN = 800; // 单段最长字符数，超出截断
        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String snippet = result.getTextContent();
            if (snippet.length() > MAX_SNIPPET_LEN) {
                snippet = snippet.substring(0, MAX_SNIPPET_LEN) + "…";
            }
            String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
            context.append(String.format("[%d] (%s) %s\n", i + 1, fileLabel, snippet));
        }
        return context.toString();
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            // 检查是否需要停止发送
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                logger.debug("检测到停止标志，跳过发送响应块");
                return;
            }
            
            // 将chunk包装成JSON格式，匹配前端期望的数据结构
            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("发送响应块到会话 {}: {}", session.getId(), jsonChunk);
            session.sendMessage(new TextMessage(jsonChunk));
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 推送思考过程数据块到前端
     * 检查 thinking 功能开关和停止标志
     */
    void sendThinkingChunk(WebSocketSession session, String chunk) {
        try {
            // 检查 thinking 功能是否启用
            if (!aiProperties.getThinking().isEnabled()) {
                return;
            }
            // 检查停止标志
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                return;
            }
            Map<String, String> chunkResponse = Map.of("type", "thinking", "chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            session.sendMessage(new TextMessage(jsonChunk));
        } catch (Exception e) {
            logger.error("发送思考块失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 推送回答内容数据块到前端
     * 检查停止标志
     */
    void sendAnswerChunk(WebSocketSession session, String chunk) {
        try {
            // 检查停止标志
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                return;
            }
            Map<String, String> chunkResponse = Map.of("type", "answer", "chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            session.sendMessage(new TextMessage(jsonChunk));
        } catch (Exception e) {
            logger.error("发送回答块失败: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(WebSocketSession session) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "completion",
                "status", "finished", 
                "message", "响应已完成",
                "timestamp", currentTime,
                "date", java.time.LocalDateTime.now().toString()
            );
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("发送完成通知到会话 {}: {}", session.getId(), notificationJson);
            session.sendMessage(new TextMessage(notificationJson));
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("error", "AI服务暂时不可用，请稍后重试");
            String errorJson = objectMapper.writeValueAsString(errorResponse);
            logger.error("发送错误消息到会话 {}: {}", session.getId(), errorJson);
            session.sendMessage(new TextMessage(errorJson));
            logger.error("已发送错误消息到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送错误消息失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 统一清理指定 session 关联的所有临时数据
     */
    public void cleanupSession(String sessionId) {
        responseBuilders.remove(sessionId);
        thinkingBuilders.remove(sessionId);
        stopFlags.remove(sessionId);
        sessionConversationIds.remove(sessionId);
        sessionUserIds.remove(sessionId);
        sessionStartTimes.remove(sessionId);
    }

    /**
     * 定时清理超过 10 分钟未完成的 stale session 数据，防止内存泄漏
     * 每 5 分钟执行一次
     */
    @Scheduled(fixedRate = 300000)
    public void cleanupStaleBuilders() {
        long now = System.currentTimeMillis();
        sessionStartTimes.entrySet().removeIf(entry -> {
            if (now - entry.getValue() > 600000) { // 10 分钟
                String sessionId = entry.getKey();
                logger.warn("定时清理残留 session 数据: {}", sessionId);
                // 清理其他 Map（sessionStartTimes 由 removeIf 负责移除，避免重复操作）
                responseBuilders.remove(sessionId);
                thinkingBuilders.remove(sessionId);
                stopFlags.remove(sessionId);
                sessionConversationIds.remove(sessionId);
                sessionUserIds.remove(sessionId);
                return true;
            }
            return false;
        });
    }

    /**
     * 停止响应 
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);
        
        // 设置停止标志
        stopFlags.put(sessionId, true);
        
        // 发送停止确认
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                "type", "stop", 
                "message", "响应已停止",
                "timestamp", currentTime,
                "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("发送停止确认到会话 {}: {}", sessionId, stopJson);
            session.sendMessage(new TextMessage(stopJson));
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        }
        
        // 清理停止标志（延迟清理，避免影响当前响应）
        new Thread(() -> {
            try {
                Thread.sleep(2000); // 等待2秒
                stopFlags.remove(sessionId);
                logger.debug("已清理停止标志，会话ID: {}", sessionId);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }
}
